print("##teamcity[compilationStarted compiler='<compiler_name>']")
print("##teamcity[message text='compiler output']")
print("##teamcity[message text='compiler output']")
print("##teamcity[message text='compiler error' status='ERROR']")
print("##teamcity[compilationFinished compiler='<compiler name>']")
