print("##teamcity[compilationStarted compiler='<compiler name>']")
print("##teamcity[message text='compiler output']")
print("##teamcity[message text='compiler output']")
print("##teamcity[message text='warning message' status='WARNING']")
print("##teamcity[inspectionType id='test' name='test inspection' description='reports inspection warnings' category='test']")
print("##teamcity[inspection typeId='test' message='inspection instance description' file='warning filename' line='111' additional attribute='additional attribute']")
print("##teamcity[inspectionType id='UnnecessaryLocalVariable' name='Redundant local variable' description='<html><body>Reports unnecessary local variables...</body></html>' category='Data flow issues']")
print("##teamcity[inspection typeId='UnnecessaryLocalVariable' message='Local variable <code>i</code> is redundant' file='src/Test.java' line='19' SEVERITY='WARNING']")
print("##teamcity[compilationFinished compiler='<compiler name>']")
